---
title: "BRC1 network"
output: html_notebook
---

```{r, include=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(GenomicRanges)
library(GenomicFeatures)
library(plyranges)

# Differential expression and ChIP analyses
library(edgeR)
library(csaw)

# Gene annotation
library(biomaRt)
library(AnnotationDbi)
library(org.At.tair.db)
library(GO.db)
library(clusterProfiler)
library(pathview)
library(GOSemSim)

ensembl = biomaRt::useMart(biomart="plants_mart",
                           dataset="athaliana_eg_gene",
                           host="https://plants.ensembl.org")
#View(listAttributes(ensembl))

# Sequence analysis
library(Biostrings)
library(BSgenome.Athaliana.TAIR.TAIR9)

# Data visualization
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(circlize)
library(randomcoloR)
library(dendextend)
library(ComplexHeatmap)
library(EnrichedHeatmap)
library(ggsci)
library(ggrepel)
library(ggpmisc)
library(directlabels)
library(WeightedCluster)

# Load custom functions
invisible(sapply(list.files(path = "./R/", pattern = "\\.R$", ignore.case = TRUE, full.names = TRUE), source, .GlobalEnv))

# Set global ggplot theme parameters
theme_update(axis.text.x = element_text(color="black"), 
             axis.text.y = element_text(color="black"),
             axis.ticks = element_line(color="black"),
             panel.border = element_rect(color="black", fill = NA),
             panel.grid.major = element_blank(), 
             panel.grid.minor = element_blank(),
             panel.background = element_blank(),
             legend.background = element_blank(),
             plot.background = element_rect(fill = "transparent", color = NA))
```

GFP:BRC1 RNAseq
```{r}
# Define parameters for differential expression statistical tests
exp_name = paste0(format(Sys.Date(),"%Y_%m_%d_"), "GFPBRC1ind_")
feature_counts = fread("./input/BRC1ind_featureCounts.count")
feature_counts = feature_counts[,c(1:6,10:12,7:9)] # Rearrange columns to have controls as first columns
sample_names = c("brc1_1","brc1_2","brc1_3",
                 "GFP_BRC1ind_1","GFP_BRC1ind_2","GFP_BRC1ind_3")
sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels= %>% (gsub('.{2}$', '', sample_names)))
design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
my_contrasts = makeContrasts(GFP_BRC1ind_vs_brc1 = GFP_BRC1ind-brc1,
                             levels=design)

# Perform statistcal tests
brc1ind_results = difexp_analysis(feature_counts=feature_counts,
                                  exp_name=exp_name,
                                  sample_names=sample_names,
                                  sample_groups=sample_groups,
                                  design=design,
                                  my_contrasts=my_contrasts)

# Store results for downstream analyses
BRC1ind_data_unfiltered = brc1ind_results$merged_tests
BRC1ind_data = brc1ind_results$filtered_tests
BRC1ind_DGEL = brc1ind_results$DGEL

# Write rpkm and filtered fold changes to output
write.table(brc1ind_results$rpkm, file = paste0("./output/",exp_name,"RPKM.txt"), row.names=F, sep="\t", quote=F)
write.table(brc1ind_results$filtered_tests, file = paste0("./output/",exp_name,"filtered_tests.txt"), row.names=F, sep="\t", quote=F, na="")

### Data visualization
# MDS plot
DGEL_input = BRC1ind_DGEL
group_labels = c(brc1 = "brc1", GFP_BRC1ind = "GFP:BRC1ind")
col_palette = pal_jco("default")(4)[c(3,1)]

mds_plot = mds_ggplot(DGEL_input,group_labels,col_palette)

custom_width = 14
ggsave(mds_plot+theme(text = element_text(size=15)), 
       filename = "./output/mds_plot_GFPBRC1ind.png",
       dpi = 600,
       units = "cm",
       width = custom_width, height = custom_width/1.386568)

# Volcano plot
vp_input = BRC1ind_data_unfiltered
comparisons = find_tests(vp_input)
volc_plot = volcano_plot(vp_input,comparisons)

ggsave(volc_plot, 
       filename = "./output/volc_plot_GFPBRC1ind.png",
       dpi = 600,
       units = "cm",
       width = 16.93, height = 12.21)
```

HBind RNAseq
```{r}
# Define parameters for differential expression statistical tests
exp_name = paste0(format(Sys.Date(),"%Y_%m_%d_"), "HBind_")
feature_counts = fread("./input/HBs_experiment_featureCounts.count")
sample_names = c("gus_1","gus_2","gus_3",
                 "hb21i_1","hb21i_2","hb21i_3",
                 "hb40i_1","hb40i_2","hb40i_3",
                 "hb53i_1","hb53i_2","hb53i_3")
sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels=unique(gsub('.{2}$', '', sample_names)))
design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
my_contrasts = makeContrasts(hb21i_vs_gus=hb21i-gus,
                             hb40i_vs_gus=hb40i-gus,
                             hb53i_vs_gus=hb53i-gus,
                             levels=design)

# Perform statistcal tests
hbind_results = difexp_analysis(feature_counts=feature_counts,
                                exp_name=exp_name,
                                sample_names=sample_names,
                                sample_groups=sample_groups,
                                design=design,
                                my_contrasts=my_contrasts)

# Store results for downstream analyses
HBind_data_unfiltered = hbind_results$merged_tests
HBind_data = hbind_results$filtered_tests
HBind_DGEL = hbind_results$DGEL

###

# x = hbind_results$list_by_contrast %>% purrr::reduce(full_join, map2, by = c("Geneid","Chr","Start","End","Strand","Length"))
# 
# 
# hbind_results$list_by_contrast %>% bind_rows() %>% pull(Geneid) %>% unique %>% length
# 
# 
# 
# z = HBind_data_unfiltered %>% filter(Geneid %in% x$Geneid)
# 
# fdr_1 = (get(fdr_colnames[1]) < 0.05)
# fc_1 = (abs(get(contrast_colnames[1])) > log2(2))
# 
# HBind_data_unfiltered %>% filter(((get(fdr_colnames[1]) < 0.05)&(abs(get(contrast_colnames[1])) > log2(2))) | 
#                                   ((get(fdr_colnames[2]) < 0.05)&(abs(get(contrast_colnames[2])) > log2(2))) |
#                                    ((get(fdr_colnames[3]) < 0.05)&(abs(get(contrast_colnames[3])) > log2(2))))

### Check filtering in diffexp_analysis


# 
# y = hbind_results$list_by_contrast
# 
# z = y[[1]]
# 
# dplyr::filter(z,fdr_colnames[1] > 0.05)
# 
# fdr_colnames = sapply(y, function(x) colnames(x)[grepl("^FDR",colnames(x))])
# contrast_colnames = sapply(y, function(x) colnames(x)[grepl("^logFC",colnames(x))])
# 
# filter_func = function(x, fdr_col, fc_col) {
#   dplyr::filter(x, (get(fdr_col) < FDRts) & (abs(get(fc_col) > FCts)))
# }
# 
# test = mapply(filter_func, test_list, fdr_colnames, contrast_colnames, SIMPLIFY = FALSE)


# Write rpkm and filtered fold changes to output
write.table(hbind_results$rpkm, file = paste0("./output/",exp_name,"RPKM.txt"), row.names=F, sep="\t", quote=F)
write.table(hbind_results$filtered_tests, file = paste0("./output/",exp_name,"filtered_tests.txt"), row.names=F, sep="\t", quote=F, na="")

### Data visualization
# MDS plot
DGEL_input = HBind_DGEL
group_labels = c(gus = "GUSind",
                 hb21i = "HB21ind",
                 hb40i = "HB40ind",
                 hb53i = "HB53ind")
col_palette = pal_jco("default")(4)[c(3,1,2,4)]

mds_plot = mds_ggplot(DGEL_input,group_labels,col_palette)

custom_width = 12
ggsave(mds_plot+theme(text = element_text(size=15)), 
       filename = "./output/mds_plot_HBind.png",
       dpi = 600,
       units = "cm",
       width = custom_width, height = custom_width/1.386568)

# Volcano plot
vp_input = HBind_data_unfiltered
comparisons = find_tests(vp_input)
volc_plot_list = lapply(comparisons, volcano_plot, edger_merged_results = vp_input)
volc_plot = ggarrange(plotlist=volc_plot_list, ncol = 3)

ggsave(volc_plot, 
       filename = "./output/volc_plot_HBind.png",
       dpi = 600,
       units = "cm",
       width = 16.93*2, height = 12.21)
```

ABA treatment RNAseq: wt, brc1, hb21hb40hb53; control/+ABA
```{r}
# Define parameters for differential expression statistical tests
exp_name = paste0(format(Sys.Date(),"%Y_%m_%d"), "_ABA_")
feature_counts = fread("./input/ABA_experiment_featureCounts.count")
sample_names = c("wt_ctr_1","wt_ctr_2","wt_ctr_3",
                 "wt_aba_1","wt_aba_2","wt_aba_3",
                 "tri_ctr_1","tri_ctr_2","tri_ctr_3",
                 "tri_aba_1","tri_aba_2","tri_aba_3",
                 "brc1_ctr_1","brc1_ctr_2","brc1_ctr_3",
                 "brc1_aba_1","brc1_aba_2","brc1_aba_3")
sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels=unique(gsub('.{2}$', '', sample_names)))
design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
my_contrasts = makeContrasts(brc1_ctr_vs_wt_ctr=brc1_ctr-wt_ctr,
                             tri_ctr_vs_wt_ctr=tri_ctr-wt_ctr,
                             wt_aba_vs_wt_ctr=wt_aba-wt_ctr,
                             brc1_aba_vs_brc1_ctr=brc1_aba-brc1_ctr,
                             tri_aba_vs_tri_ctr=tri_ctr-tri_aba,
                             levels=design)

# Perform statistcal tests
aba_results = difexp_analysis(feature_counts=feature_counts,
                                exp_name=exp_name,
                                sample_names=sample_names,
                                sample_groups=sample_groups,
                                design=design,
                                my_contrasts=my_contrasts)

# Store results for downstream analyses
aba_data_unfiltered = aba_results$merged_tests
aba_data = aba_results$filtered_tests
aba_DGEL = aba_results$DGEL

# Write rpkm and filtered fold changes to output
write.table(aba_results$rpkm, file = paste0("./output/",exp_name,"RPKM.txt"), row.names=F, sep="\t", quote=F)
write.table(aba_results$filtered_tests, file = paste0("./output/",exp_name,"filtered_tests.txt"), row.names=F, sep="\t", quote=F, na="")

### Data visualization
# MDS plot
DGEL_input = aba_DGEL
group_labels = c(wt_ctr = "wt",
                 wt_aba = "wt + ABA",
                 tri_ctr = "hb21hb40hb53",
                 tri_aba = "hb21hb40hb53 + ABA",
                 brc1_ctr = "brc1",
                 brc1_aba = "brc1 + ABA")
col_palette = c("#868686FF","#565656","#0073C2FF", "#005693","#EFC000FF", "#BE9800")

mds_plot = mds_ggplot(DGEL_input,group_labels,col_palette)

custom_width = 16
ggsave(mds_plot+theme(text = element_text(size=15)), 
       filename = "./output/mds_plot_ABA.png",
       dpi = 600,
       units = "cm",
       width = custom_width, height = custom_width/1.386568)

# Volcano plot (with FC > 2 threshold)
vp_input = aba_data_unfiltered
comparisons = find_tests(vp_input)
volc_plot_list = lapply(comparisons, volcano_plot, edger_merged_results = vp_input)

volc_plot1 = ggarrange(plotlist=volc_plot_list[1:2], ncol = 2)
ggsave(volc_plot1, 
       filename = "./output/volc_plot_brc1_triple.png",
       dpi = 600,
       units = "cm",
       width = 16.93*(4/3), height = 12.21)

volc_plot2 = ggarrange(plotlist=volc_plot_list[3:5], ncol = 3)
ggsave(volc_plot2, 
       filename = "./output/volc_plot_ABA.png",
       dpi = 600,
       units = "cm",
       width = 16.93*2, height = 12.21)

# Volcano plot (with FC > 2 threshold)
comparisons = find_tests(vp_input)
volc_plot_list = lapply(comparisons, volcano_plot, edger_merged_results = vp_input,logfc_threshold = 0)

volc_plot1 = ggarrange(plotlist=volc_plot_list[1:2], ncol = 2)
ggsave(volc_plot1, 
       filename = "./output/volc_plot_brc1_triple_no_fc_cut.png",
       dpi = 600,
       units = "cm",
       width = 16.93*(4/3), height = 12.21)

volc_plot2 = ggarrange(plotlist=volc_plot_list[3:5], ncol = 3)
ggsave(volc_plot2, 
       filename = "./output/volc_plot_ABA_no_fc_cut.png",
       dpi = 600,
       units = "cm",
       width = 16.93*2, height = 12.21)
```

GFP:BRC1 ChIP
```{r}
# Generate consensus peak annotation (from MACS2 peak calling)
# Merge peaks called in at least 2 replicates (adapted from https://ro-che.info/articles/2018-07-11-chip-seq-consensus)
# Used three 1value threshold to call peaks in MACS2 (qval < 0.05, 0.01 or 0.001)
# Consensus with MACS2 qval < 0.001
peak_file_list = list.files(path = "./input/", pattern="^BRC1_ChIP.*q0001.*\\.narrowPeak$", full.names=TRUE)
peak_names = peak_file_list %>% str_extract("BRC1_ChIP*.")

macs2_consensus_q0001 = get_consensus_peaks(peak_file_list, peak_names)
write_bed(macs2_consensus_q0001, file = "./output/macs2_q0001_consensus.bed")

# Consensus with MACS2 qval < 0.01
peak_file_list = list.files(path = "./input/", pattern="^BRC1_ChIP.*q001.*\\.narrowPeak$", full.names=TRUE)
peak_names = peak_file_list %>% str_extract("BRC1_ChIP*.")

macs2_consensus_q001 = get_consensus_peaks(peak_file_list,peak_names)
write_bed(macs2_consensus_q001, file = "./output/macs2_q001_consensus.bed")

# Consensus with MACS2 qval < 0.05
peak_file_list = list.files(path = "./input/", pattern="^BRC1_ChIP.*q0\\.05.*\\.narrowPeak$", full.names=TRUE)
peak_names = peak_file_list %>% str_extract("BRC1_ChIP*.")

macs2_consensus_q005 = get_consensus_peaks(peak_file_list,peak_names)
write_bed(macs2_consensus_q005, file = "./output/macs2_q005_consensus.bed")

#####
# csaw to quantify peak strength (TO DO: CLEAN CODE)

# 1- Check fragment length to precisely quantify peak signal (calculate cross-correlation coefficient (ccf)) ####
# "For weak signal datasets, the read-length peak will start to dominate."
# https://hbctraining.github.io/Intro-to-ChIPseq/lessons/06_combine_chipQC_and_metrics.html
bam_files = list.files(path = "D:/PERSONAL_SACO/Cubas lab/BRC1 ChIPseq/sam_output/", pattern=".*\\.bam$", full.names=TRUE)
bam_files = bam_files[c(4:6,1:3)] # reorder columns so controls are first
bam_filenames = bam_files %>% str_match("ChIP\\d|Input\\d") %>% as.vector

# Load csaw Parameters and turn on removal of duplicate reads (use param=dedup.on as param object for cross-correlation studies)
param = readParam()
dedup.on = initialize(param, dedup=TRUE)

# Calculate cross-correlation for each .bam file and make dataframe for plotting with labels for max ccf for each file
ccf_list = lapply(bam_files, correlateReads, param=dedup.on) %>% `names<-`(bam_filenames)

ccf_list_plot = as.data.frame(do.call(cbind, ccf_list)) %>% 
  rownames_to_column("bp") %>% mutate (bp = as.numeric(bp)) %>% 
  pivot_longer(-bp,names_to = "sample",values_to = "ccf")

ccf_labels = sapply(ccf_list, maximizeCcf, ignore=100) %>% as.data.frame %>% rownames_to_column %>% setNames(c("sample","max_ccf"))

# Calculate average correlation profile across all the IP bam files
ccf_total = bam_files[4:6] %>% correlateReads(param=dedup.on)
max_total_ccf = maximizeCcf(ccf_total, ignore=100)

# Plot ccf per file
ggplot(ccf_list_plot, aes(x = bp, y = ccf, group = sample)) +
  geom_line() +
  geom_vline(aes(xintercept = max_ccf), ccf_labels) +
  geom_label(inherit.aes = FALSE, data = ccf_labels, 
             aes(label = paste0("Max ccf (>100 bp): ",max_ccf)), label.size = NA, alpha = 0.5,
             x = -Inf, y = Inf,
             hjust = 0, vjust = 1) +
  coord_cartesian(xlim = c(0,300)) +
  scale_x_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(~sample)


# 2- Count peak signal using common ccf ####
data = windowCounts(bam_files, ext=max_total_ccf, width=10, spacing=10)

# Remove "unintersting regions" (regions withour peaks)
binned = windowCounts(bam_files, bin=TRUE, width=10000)
keep = filterWindowsGlobal(data, binned)$filter > log2(2)
data2 = data[keep,]

data2 = normFactors(binned, se.out=data2)

# Create DGEList object to quantify peak signal
sample_names = bam_filenames
sample_groups = gsub('.{1}$', '', sample_names) %>% factor(levels=unique(gsub('.{1}$', '', sample_names)))
design = model.matrix(~sample_groups)

DGEL = asDGEList(data2, group = sample_groups)
rownames(DGEL$samples) = sample_names

DGEL = estimateDisp(DGEL, design)
fit = glmQLFit(DGEL, design, robust=TRUE)
results = glmQLFTest(fit)

merged = mergeResults(data2, results$table, tol=200L) # merge peaks closer than 200 bp

# Filter results for significance (FDR), size > 10 bp, score > 0 (enriched in IP)
is.sig = merged$combined$FDR <= 0.05
csaw_result = merged$regions[is.sig]
csaw_result$score = merged$combined$rep.logFC[is.sig]
csaw_result$peak_width = width(csaw_result)
csaw_result = csaw_result %>% filter((score > 0) & (peak_width > 10))
names(csaw_result) = paste0("region_", 1:length(csaw_result))

export(csaw_result, "./output/test_csaw.bed")

# 2b - csaw with good replicates
bam_files2 = bam_files[-c(1,4)]
bam_filenames2 = bam_filenames[-c(1,4)]

data = windowCounts(bam_files2, ext=max_total_ccf, width=10, spacing=10)

# remove "unintersting regions"
binned = windowCounts(bam_files2, bin=TRUE, width=10000)
keep = filterWindowsGlobal(data, binned)$filter > log2(2)
data2 = data[keep,]

data2 = normFactors(binned, se.out=data2)

# Create DGEList object
sample_names = bam_filenames2
sample_groups = gsub('.{1}$', '', sample_names) %>% factor(levels=unique(gsub('.{1}$', '', sample_names)))
design = model.matrix(~sample_groups)

DGEL = asDGEList(data2, group = sample_groups)
rownames(DGEL$samples) = sample_names

DGEL = estimateDisp(DGEL, design)
fit = glmQLFit(DGEL, design, robust=TRUE)
results = glmQLFTest(fit)

merged = mergeResults(data2, results$table, tol=200L) # merge peaks closer than 200 bp

# Filter results for significance (FDR), size > 10 bp, score > 0 (enriched in IP)
is.sig = merged$combined$FDR <= 0.05
csaw_result = merged$regions[is.sig]
csaw_result$score = merged$combined$rep.logFC[is.sig]
csaw_result$peak_width = width(csaw_result)
csaw_result = csaw_result %>% filter((score > 0) & (peak_width > 10))
names(csaw_result) = paste0("region_", 1:length(csaw_result))

export(csaw_result, "./output/test_csaw_rep1_2.bed")

#####

# Plot peak location respective of TSS. With "heatmap"
# Create GRanges object with all arabidopsis genes from ensembl .gtf file
ath_gtf = read_gff("./input/Arabidopsis_thaliana.TAIR10.52.gtf.gz")
ath_genes = ath_gtf %>% filter(type == "gene")
tss = ath_genes %>% resize(width=1, fix='start') %>% select(gene_id) %>% `names<-`(.$gene_id) %>% sort

peak_files = list.files(path = "./output/", pattern = ".bed", all.files = TRUE, full.names = TRUE)

macs_peak_files = peak_files %>% str_match(".*macs2_q.*\\.bed$") %>% na.omit() %>% as.vector
peak_file_names = sapply(strsplit(macs_peak_files, "_"), function(x) x[2])
list1 = lapply(macs_peak_files, read_bed) %>% GRangesList() %>% `names<-`(peak_file_names)

csaw_peak_files = peak_files %>% str_match(".*csaw.*\\.bed$") %>% na.omit() %>% as.vector
peak_file_names = c("csaw","csaw12")
list2 = lapply(csaw_peak_files, read_bed) %>% GRangesList() %>% `names<-`(peak_file_names)

# Example 1. Compare csaw to MACS2 peaks ####
list3 = c(list1,list2)

example = batch_enrichedheatmaps(list3, tss = tss, 
                                 anno_color = "black", 
                                 show_heatmap_legend = TRUE)

figure_filename = paste0("./output/test_",ext5,"_",ext3,".png")

png(figure_filename, width = 30, height = 15, units = "cm", res = 300)
draw(example, 
     ht_gap = unit(1, "cm"),
     padding = unit(c(0, 0.5, 0, 0.02), "cm"))
dev.off()

# Example 2. Plot HB Dapseq data relative to TSS ####
peak_files = list.files(path = "./input/dapseq_data/", pattern = "*.narrowPeak", all.files = TRUE,
           full.names = TRUE) %>% str_extract(".*HB_ATHB21.*|.*HB_ATHB40.*|.*HB_ATHB53.*") %>% as.vector %>% discard(is.na)

peak_file_names = c("HB21","HB21_amp","HB40","HB40_amp","HB53","HB53_amp")
peak_list = lapply(peak_files, read_narrowpeaks) %>% GRangesList() %>% `names<-`(peak_file_names) %>% `seqlevelsStyle<-`(seqlevelsStyle(tss))

dapseq_htlist = batch_enrichedheatmaps(peak_list,
                                       tss = tss,
                                       anno_color = "black",
                                       value_column = "signalValue",
                                       heatmap_col_breaks = c(0,0.99),
                                       show_heatmap_legend = TRUE)

figure_filename = paste0("./output/HB_peak_location_",ext5,"_",ext3,".png")
  
png(figure_filename, width = 30, height = 15, units = "cm", res = 300)
draw(dapseq_htlist, 
     ht_gap = unit(1, "cm"),
     padding = unit(c(0, 0.5, 0, 0.02), "cm"))
dev.off()



# Select genes with peak in their 3kb_up+1kb_dn of TSS ####
# Retrieve 3kb upstream and 1kb downstream of TSS (using plyranges)
ath_3kup_1kdown = ath_genes %>% anchor_5p %>% mutate(width = 1) %>% stretch(5999) %>%
  anchor_5p %>% stretch(-2000) %>% `mcols<-`(value = list("gene_id" = .$gene_id))

#####
# TO DO Make function to generate annotation_df from list of direct targets
hb_peak_list = peak_list[c(1,3,5)]
hb_de_list = hbind_results$list_by_contrast

test = make_anno_df(hb_de_list,hb_peak_list,
                    target_region = ath_3kup_1kdown,
                    peak_name_column = "name")


brc1_de_list = brc1ind_results$list_by_contrast
brc1_peaks = GRangesList(macs2_consensus_q005,macs2_consensus_q001,macs2_consensus_q0001) %>% `names<-`(c("q0.05","q0.01","q.0.001"))

brc1_dt = get_direct_targets(brc1_peaks$q0.05,brc1_de_list[[1]],target_region = ath_3kup_1kdown)

brc1_de_direct_targets = brc1_de_list[[1]] %>% filter(Geneid %in% brc1_dt)

##### 
test = make_anno_df(brc1_de_direct_targets,hb_peak_list,
                    target_region = ath_3kup_1kdown,
                    peak_name_column = "name")

test2 = make_anno_df(brc1_de_direct_targets,brc1_peaks,
                     target_region = ath_3kup_1kdown,
                     peak_name_column = "peak_name",
                     gene_id_column = "Geneid")


x = get_direct_targets(brc1_peaks[[1]], de_file=brc1_de_direct_targets, target_region = ath_3kup_1kdown)

anno_df = cbind(test2,test)

# heatmap
input = brc1_de_direct_targets %>% select(c(Geneid, logFC_GFP_BRC1ind_vs_brc1)) %>% left_join(HBind_data, by =
                                                                                      "Geneid") %>%
  left_join(aba_data, by = "Geneid") %>%
  select(
    c(
      Geneid,
      logFC_GFP_BRC1ind_vs_brc1,
      logFC_brc1_ctr_vs_wt_ctr,
      logFC_wt_aba_vs_wt_ctr,
      logFC_hb21i_vs_gus,
      logFC_hb40i_vs_gus,
      logFC_hb53i_vs_gus
    )
  ) 

# input = HBind_data %>% 
#   select(c(Geneid,logFC_hb21i_vs_gus,logFC_hb40i_vs_gus,logFC_hb53i_vs_gus)) 
# input = input %>%
#   filter(Geneid %in% brc1_de$Geneid)
# 

brc1_de = aba_data_unfiltered %>% filter(FDR_brc1_ctr_vs_wt_ctr<0.05)
brc1_de_anno = ifelse(input$Geneid %in% brc1_de$Geneid, 1,0) %>% `names<-`(input$Geneid)

brc1_array = read.table("./input/BRC1dep_PC2013.txt",header = TRUE) %>% mutate(Geneid = toupper(Geneid))
brc1_array_anno = ifelse(input$Geneid %in% brc1_array$Geneid, 1,0) %>% `names<-`(input$Geneid)

# Create list of coloring functions for annotation dataframe
anno_col_fun = colorRamp2(c(0, 1), c("white", "black")) 

col_fun_list = list()
for(i in colnames(anno_df)){
  col_fun_list[[i]] = anno_col_fun
}

ha = HeatmapAnnotation(df = anno_df,
                       which = "row",
                       # annotation_label = c("brc1 de","brc1 array","BRC1 csaw","BRC1 q005", "BRC1 q001", "BRC1 q0001",
                       #                      "HB21 Dapseq","HB40 Dapseq","HB53 Dapseq"),
                       annotation_name_side="top",
                       annotation_name_rot=45,
                       show_legend = FALSE,
                       col = col_fun_list)


ht_input = input %>% column_to_rownames("Geneid") %>% as.matrix()

Heatmap(ht_input[,-(2:3)],
        clustering_method_rows = "ward.D2",
        right_annotation = ha,
        show_row_names = FALSE,
        #show_column_names = FALSE
        )

Heatmap(ht_input[,c(1,4:6)],
        clustering_method_rows = "ward.D2",
        right_annotation = ha,
        show_row_names = FALSE,
        #show_column_names = FALSE
        )
```

To check number of peaks depending on qvalue filter for MACS2 narrowPeak files with
```{r}
macs_q1_files = list.files(path = "./input/gema/peaks/macs2_ChIP/", pattern = "\\.narrowPeak$", full.names = TRUE)
peak_names = c("ChIP2","ChIP3","ChIP7")
macs_q1 = lapply(macs_q1_files, read_narrowpeaks) %>% `names<-`(peak_names)

qvals = -log10(c(0.1,0.05,0.01,0.001))

tmp_func = function(x,y) { plyranges::filter(x, qValue > y) %>% length }

a = list()
for(q in qvals){
  q_val = 10^-q %>% paste0("qval_",.)
  a[[q_val]] = sapply(macs_q1, tmp_func, q)
}

tmp_func2 = function(x,y) { 
  plyranges::filter(x, qValue > y)
  }

b = list()
for(q in qvals){
  q_val = 10^-q %>% paste0("qval_",.)
  test = sapply(macs_q1, tmp_func2, q)
  z = get_consensus_peaks_GRangesList(test,peak_names)
  b[q_val] = (length(z))
}

as.data.frame(a) %>% rbind("Consensus" = b)
```

(to do) Compare BRC1dep
```{r}
BRC1dep_PC2013 = fread("./input/BRC1dep_PC2013.txt") %>% mutate(Geneid = toupper(Geneid))
BRC1dep_PC2013$logFC %>% hist(breaks = 100)

# To do: compare microarray results to RNAseq
```

(to do) BRC1 network
```{r}
macs2_consensus_q0001
macs2_consensus_q001
macs2_consensus_q005
ath_3kup_1kdown

ABA_results
HBind_results
GFPBRC1ind_results


###
test = ABA_results %>% select(c(Geneid,logFC_brc1_ctr_vs_wt_ctr,FDR_brc1_ctr_vs_wt_ctr,logFC_tri_ctr_vs_wt_ctr,FDR_tri_ctr_vs_wt_ctr)) %>% 
  filter(FDR_brc1_ctr_vs_wt_ctr < 0.05)

#### BUILD MATRIX FOR HEATMAP
data = GFPBRC1ind_results
gene_symbol = suppressMessages(mapIds(org.At.tair.db,
                                      column = "SYMBOL",
                                      keys = data$Geneid,
                                      keytype = "TAIR",
                                      multiVals = "first"))

mat_row_labels = apply(cbind(data$Geneid, gene_symbol), 1, 
        function(x) paste(x[!is.na(x)], collapse = " "))

logfc_column = "logFC_GFP_BRC1ind_vs_brc1"

filtered_data = data %>% dplyr::select(all_of(logfc_column)) %>% 
  arrange(desc(get(logfc_column))) %>% 
  as.matrix %>% `rownames<-`(mat_row_labels) %>% `colnames<-`(c("GFPBRC1ind"))

Heatmap(filtered_data,
        #clustering_method_rows = "ward.D2",
        #clustering_method_columns = "ward.D2",
        row_order = rownames(filtered_data),
        row_names_gp = gpar(fontsize = 4))


```

(to do) GO, Upset plots
```{r}
##### 
# IN PROGRESS:
### GO enrichment and GSEA 

# Generate GO object with Information Content for Semantic Similarity analyses
if(!exists("athGO")){
  athGO = godata("org.At.tair.db", ont="BP")
}

# Object to match GO ID with GO definitions
GO_def = AnnotationDbi::select(GO.db,
                              keys=(keys(GO.db)),
                              columns=c("GOID","TERM","DEFINITION"),
                              keytype="GOID")

# Object to find GO common ancestor
GO_anc = as.list(GOBPANCESTOR)

# Object to match GO ID with GO definitions
GO_def = AnnotationDbi::select(GO.db,
                              keys=(keys(GO.db)),
                              columns=c("GOID","TERM","DEFINITION"),
                              keytype="GOID")

# Format input data for GO and GSEA analyses (vector of Fold-change named with gene IDs)
fc_column = colnames(filtered_tests_output)[grepl(c("^logFC"),colnames(filtered_tests_output))] 
GO_input = filtered_tests_output %>% dplyr::select(Geneid, all_of(fc_column))

ranked_genes = setNames(GO_input[,fc_column],
                        GO_input$Geneid) %>% sort %>% rev

genes_up = ranked_genes[ranked_genes > 0]
genes_dn = ranked_genes[ranked_genes < 0]

# Perform GO enrichment analysis with up- and down-regulated genes
GOenrich_up = enrichGO(gene = names(genes_up),
                OrgDb = org.At.tair.db,
                keyType = "TAIR",
                ont = "BP",
                pAdjustMethod = "BH",
                qvalueCutoff = 0.05)
GOenrich_up %>% as.data.frame() %>% pull(ID) %>% length()

goplot(GOenrich_up)

GOenrich_dn = enrichGO(gene = names(genes_dn),
                OrgDb = org.At.tair.db,
                keyType = "TAIR",
                ont = "BP",
                pAdjustMethod = "BH",
                qvalueCutoff = 0.05)

goplot(GOenrich_dn)

#####
# Clustering of GO enriched terms
# Generate object with GO Semantic Similarity and Information Content


# 3- Summarize GO by semantic similarity
# Get common GO terms and calculate semantic similarity between them
GO_data = as.data.frame(GOenrich_dn) # to query for GO IDs and descriptions

GO_IDs = GO_data %>% pull(unique(ID))
ss_rel = mgoSim(GO_IDs, GO_IDs, semData=athGO, measure="Rel", combine=NULL)

# Calculate optimal cluster number "mathematically"
#### WeighedCluster
GO_hclust = (1 - ss_rel) %>% as.dist %>%
  hclust(method = "ward.D2")

GO_hclust_n = length(GO_hclust$order)

clustrange = as.clustrange(GO_hclust, diss=(1 - ss_rel), ncluster = GO_hclust_n)

# R2 and R2-sq will always give maximum number of clusters as optimal (see WeighedCluster user's guide)
# RHC is reverse HC, so max value is ideal
clustrange_summary = summary(clustrange, max.rank=1) %>% rownames_to_column("method") %>% filter(!(method %in% c("R2","R2sq"))) 

best_cluster = clustrange_summary$`1. N groups` %>% mode_value()

best_cluster

plot(clustrange, 
     stat=c("PBC","ASWw", "ASW","HG", "HGSD", "RHC"), 
     norm="zscore",lwd=3)

pamRange <- wcKMedRange((1 - ss_rel), kvals=2:GO_hclust_n)
pamrange_summary = summary(pamRange, max.rank=2)
best_cluster_pam = pamrange_summary$`1. N groups` %>% mode_value()

best_cluster_pam

plot(pamRange, 
     stat=c("PBC","ASWw", "ASW","HG", "HGSD", "RHC"), 
     norm="zscore",lwd=3)
####
which.peaks <- function(x,partial=TRUE,decreasing=FALSE){
     if (decreasing){
         if (partial){
             which(diff(c(FALSE,diff(x)>0,TRUE))>0)
         }else {
             which(diff(diff(x)>0)>0)+1
         }
     }else {
         if (partial){
             which(diff(c(TRUE,diff(x)>=0,FALSE))<0)
         }else {
             which(diff(diff(x)>=0)<0)+1
         }
     }
 }

test = pamRange$stats$PBC

which.peaks(test)
sapply(pamRange$stats, which.peaks)

###
# Visualize GO similarity
row_labs = structure(paste(GO_IDs,GO_data$Description), names = paste0(GO_IDs))
col_fun = colorRamp2(c(0,1), c("white", "red"))

test = structure(GO_data$p.adjust, names = paste0(GO_IDs))
pvalue_col_fun = colorRamp2(c(0, 0.05), c("green", "white")) 

ha = HeatmapAnnotation(pvalue = test,
                       which = "row", 
                       annotation_label = "adj. p-val.",
                       annotation_name_side="top",
                       annotation_name_rot=45,
                       col = list(pvalue = pvalue_col_fun),
                       annotation_legend_param = list(
                         pvalue = list(
                           at = c(0, 0.05))))

GO_heatmap = Heatmap(ss_rel,
                     name = "Similarity",
                     clustering_method_rows = "ward.D2",
                     clustering_method_columns = "ward.D2",
                     col = col_fun,
                     row_labels = row_labs[rownames(ss_rel)],
                     row_names_max_width = max_text_width(row_labs),
                     right_annotation = ha,
                     show_column_names = FALSE
                     )

GO_heatmap

# Visualize GO clustering
dd = (1 - ss_rel) %>% as.dist %>%
  hclust(method = "ward.D2") %>% as.dendrogram(hang = -1) %>%
  set("labels_cex", 0.6)

labels(dd) = GO_data$Description[match(labels(dd), GO_data$ID)]

par(mar = c(1, 1, 1, 20),
    xpd = NA)
plot(dd, horiz = T)


# In this case, upon visual inspection (GO_heatmap) we see three clusters. Replot with colors to visualize
cluster_number = 15
div_pal = distinctColorPalette(cluster_number)

clusters = cutree(dd, cluster_number,order_clusters_as_data=T) %>% 
  as.factor() %>% fct_inorder() %>% fct_rev()

dd = (1 - ss_rel) %>% as.dist %>%
  hclust(method = "ward.D2") %>% as.dendrogram(hang = -1) %>%
  set("labels_cex", 0.6) %>% 
  set("branches_k_color", k=cluster_number, value = div_pal) %>% 
  set("labels_col", k=cluster_number, value = div_pal)

labels(dd) = GO_data$Description[match(labels(dd), GO_data$ID)]

par(mar = c(1, 1, 1, 20),
    xpd = NA,
    bg = "grey50"
    ) 
plot(dd, horiz = T)

# 4- Select representative term for each cluster
# Retrieve Information Content for each term
tmp = GO_data %>% 
  mutate(Cluster = factor(clusters[match(Description, names(clusters))])) %>%
  dplyr::select(c("ID","Description","Cluster")) %>% mutate(IC = athGO@IC[ID])

# Retrieve ancestral GO terms
tmp2 = GO_anc[tmp$ID] %>% stack() %>% 
  mutate(CL = tmp$Cluster[match(ind,tmp$ID)]) %>% 
  data.table()

# Obtain representative ancestral GO term by IC^2 (if there is a tie it will return only one term)
reprGO = tmp2[,.N,by=c("CL","values")] %>% 
  mutate(IC = athGO@IC[values]) %>% 
  mutate(importance = (IC^2)) %>% group_by(CL) %>% 
  dplyr::slice(which.max(importance)) %>% 
  #dplyr::filter(importance == max(importance,na.rm=T)) %>%
  ungroup() %>% mutate(Desc = GO_def$TERM[match(values,GO_def$GOID)])

reprGO


####




# KEGG enrichment 
# search_kegg_organism('ath', by='kegg_code')

# To do, merge up and down regulated pathways for plotting together
KEG_enrich_up = enrichKEGG(gene         = names(genes_up),
                           organism     = "ath",
                           pvalueCutoff = 0.05)

KEG_enrich_dn = enrichKEGG(gene         = genes_dn$Geneid,
                           organism     = "ath",
                           pvalueCutoff = 0.05)

KEGG_ids = KEG_enrich_up %>% as.data.frame() %>% pull(ID)
KEGG_ids2 = KEG_enrich_dn %>% as.data.frame() %>% pull(ID)

#browseKEGG(KEG_enrich_up, KEGG_ids[1])

pathview(gene.data  = genes_up,
         pathway.id = KEGG_ids[1],
         species    = "ath",
         gene.idtype = "TAIR",
         gene.annotpkg = "org.At.tair.db",
         limit      = list(gene=max(abs(genes_up)), cpd=1))

#####
# Upset plot to see overlap
# filtered_data = filtered_tests_output %>% 
#   dplyr::select(logFC_gus_vs_hb21i,logFC_gus_vs_hb40i,logFC_gus_vs_hb53i) %>% 
#   `colnames<-`(c("HB21ind","HB40ind","HB53ind"))
# 
# HB21up = filtered_data %>% filter(HB21ind > 1) %>% rownames %>% list %>% `names<-`(paste0("HB21ind up (",length(unlist(.)),")"))
# HB21dn = filtered_data %>% filter(HB21ind < -1) %>% rownames %>% list %>% `names<-`(paste0("HB21ind down   (",length(unlist(.)),")"))
# HB40up = filtered_data %>% filter(HB40ind > 1) %>% rownames %>% list %>% `names<-`(paste0("HB40ind up   (",length(unlist(.)),")"))
# HB40dn = filtered_data %>% filter(HB40ind < -1) %>% rownames %>% list %>% `names<-`(paste0("HB40ind down   (",length(unlist(.)),")"))
# HB53up = filtered_data %>% filter(HB53ind > 1) %>% rownames %>% list %>% `names<-`(paste0("HB53ind up   (",length(unlist(.)),")"))
# HB53dn = filtered_data %>% filter(HB53ind < -1) %>% rownames %>% list %>% `names<-`(paste0("HB53ind down   (",length(unlist(.)),")"))
# 
# listInput = c(HB21up,HB40up,HB53up,HB21dn,HB40dn,HB53dn)
# 
# ggupset_input = list_to_matrix(listInput) %>% as.data.frame %>%
#   rownames_to_column("GeneID") %>%
#   gather(-GeneID, key = "sample", value = "value") %>% 
#   filter(value == 1) %>% 
#   dplyr::select(-value) %>% 
#   group_by(GeneID) %>%
#   summarize(sample = list(sample), .groups = "drop_last")
# 
# ###UpSet plot:
# UPSET_plot = ggplot(ggupset_input, aes(x=sample)) +
#   geom_bar() +
#   scale_y_continuous("Number of\nGenes", expand = expansion(mult = c(0, .25))) +
#   geom_text(stat = "count",
#             aes(label=..count..),
#             hjust = -.1, 
#             size = 2,
#             angle = 90) +
#   scale_x_upset(name = "", order_by = "freq", 
#                 sets = c(names(listInput)),
#                 n_intersections = 14) +
#   theme_classic() +
#   theme(axis.text.x = element_text(color="black"), 
#         axis.text.y = element_text(color="black"),
#         axis.ticks = element_line(color="black"),
#         plot.margin = unit(c(5.5,5.5,5.5,53), "pt"))
# # Heatmap with significant genes:
# 
# 
# mat = all_vs_ctr[,7:9]
# 
# Heatmap(mat)

```

# Extra code
```{r}
# ##### Plot logFC and chip peak strength
# BRC1ind_data
# 
# #csaw_result_filtered = csaw_result[width(csaw_result)>10]
# 
# test = find_overlaps(csaw_result_filtered,ath_3kup_1kdown) %>% `names<-`(paste0(names(.),"_",.$name))
# 
# test2 = as.data.frame(test)
# 
# test3 = BRC1ind_data %>% select("Geneid","logFC_GFP_BRC1ind_vs_brc1")
# 
# test4 = left_join(test2,test3,by = (setNames("Geneid","name")))
# 
# test5 = test4 %>% filter(!is.na(logFC_GFP_BRC1ind_vs_brc1))
# 
# ggplot(test5,aes(log2(score),abs(logFC_GFP_BRC1ind_vs_brc1))) +
#   geom_point()
# 
# 
# 
# 
# 
# 
# ##
# peak_granges = peak_list$HB21
# 
# hb = "hb21"
# fc_column = paste0("logFC_",hb,"i_vs_gus")
# fdr_column = paste0("FDR_",hb,"i_vs_gus")
# 
# hb21_de_data = HBind_data_unfiltered %>% select(Geneid,fc_column,fdr_column) %>% filter(get(fdr_column) < 0.05) %>% 
#   `colnames<-`(c("Geneid","logFC","FDR")) %>% select("Geneid","logFC")
# 
# peak_data = find_overlaps(peak_granges,ath_3kup_1kdown) %>% `names<-`(paste0(.$name.x,"_",.$name.y)) %>% as.data.frame
# 
# diffexp_data = hb21_de_data
# 
# data_for_plot = left_join(peak_data,diffexp_data,by = (setNames("Geneid","name.y"))) %>% drop_na()
# 
# ggplot(data_for_plot, aes(x=log2(signalValue),y=(logFC))) +
#   geom_point()



#fiter csaw by >10 and positive score
# filtered_list2 = lapply(list2, function(x) { plyranges::mutate(x,peak_width = width(x)) } ) %>% 
#   lapply(., function(x) { plyranges::filter(x,peak_width >10)}) %>% 
#   lapply(., function(x) { plyranges::filter(x,score>0)}) %>% `names<-`(paste0(peak_file_names,"_fil"))




# ### To do: retrieve SMXL expression level in buds
# feature_counts = fread("./input/2022_03_10_feature_counts_experiment_1_exons.txt")
# counts = feature_counts %>% dplyr::select(-c(Geneid,Chr,Start,End,Strand,Length)) %>% `colnames<-`(sample_names)
# gene_info = feature_counts %>% dplyr::select(c(Geneid,Chr,Start,End,Strand,Length))
# sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels=unique(gsub('.{2}$', '', sample_names)))
# 
# # Build design and contrasts for statistical tests
# design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
# 
# # Build DGEList object and normalize by library size
# DGEL_object = DGEList(counts = counts, 
#                       genes = gene_info,
#                       group = sample_groups) %>% calcNormFactors()
# 
# # Create RPKM object
# RPKM_object = rpkm(DGEL_object, gene.length = "Length") %>% as.data.frame %>% cbind("gene_id"=DGEL_object$genes$Geneid,.)
# 
# test = add_gene_annotation(RPKM_object,gene_id_column = "gene_id")
# 
# test %>% dplyr::filter(!grepl("BRC1",gene_symbol))
# 
# test %>% filter(str_detect(gene_symbol, "SMXL6|SMXL7|SMXL8")) %>% select(c("gene_id","gene_symbol",contains("ctr")))
# 
# write.table(test, file = paste0("./output/",exp_name,"RPKM_exon_count.txt"), row.names=F, sep="\t", quote=F)
# 
# ####
# ```
# 
# Compare with JR featurecounts data:
# ```{r}
# feature_counts_rds = readRDS("./input/featureCounts.rds")
# 
# feature_counts = cbind(feature_counts_rds$annotation, feature_counts_rds$counts) %>% dplyr::rename(Geneid ="GeneID")
# 
# # Experiment name and date of analysis for output files:
# exp_name = paste0(format(Sys.Date(),"%Y_%m_%d"), "_HBind_")
# 
# # Extract data to build DGEList object to process with edgeR
# sample_names = c("gus_1","gus_2","gus_3",
#                  "hb21i_1","hb21i_2","hb21i_3",
#                  "hb40i_1","hb40i_2","hb40i_3",
#                  "hb53i_1","hb53i_2","hb53i_3")
# 
# counts = feature_counts %>% dplyr::select(-c(Geneid,Chr,Start,End,Strand,Length)) %>% dplyr::select(19:30) %>% `colnames<-`(sample_names)
# gene_info = feature_counts %>% dplyr::select(c(Geneid,Chr,Start,End,Strand,Length))
# sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels=unique(gsub('.{2}$', '', sample_names)))
# 
# DGEL_object = DGEList(counts = counts, 
#              genes = gene_info,
#              group = sample_groups) %>% calcNormFactors()
# 
# # Create RPKM object
# RPKM_object = rpkm(DGEL_object, gene.length = "Length") %>% as.data.frame %>% cbind("gene_id"=DGEL_object$genes$Geneid,.)
# 
# write.table(RPKM_object, file = paste0("./output/",exp_name,"RPKM_JR.txt"), row.names=F, sep="\t", quote=F)
# 
# # Remove genes with low RPKM counts
# RPKM_cutoff = 1
# 
# drop = DGEL_object %>% rpkm %>% rowMeans %>% `<`(RPKM_cutoff) %>% which #get index of genes below threshold
# 
# DGEL_object_filtered = DGEL_object[-drop, ,keep.lib.sizes=FALSE] %>% calcNormFactors
# 
# # MDS plot (distance calculated from 500 top genes with highest deviation pairwise between groups
# mds = plotMDS(DGEL_object_filtered, plot=FALSE)
# dim1_label = paste0(mds$axislabel," 1 (",(mds$var.explained[1] * 100 ) %>% round(1)," %)")
# dim2_label = paste0(mds$axislabel," 2 (",(mds$var.explained[2] * 100 ) %>% round(1)," %)")
# 
# MDS_plot = data.frame(Dim1 = mds$x, Dim2 = mds$y, Group = DGEL_object_filtered$samples$group) %>% 
#   mutate(treatment = recode(Group, 
#                             "gus" = "GUSind",
#                             "hb21i" = "HB21ind",
#                             "hb40i" = "HB40ind",
#                             "hb53i" = "HB53ind"))
# 
# custom_jco = pal_jco("default")(4)[c(3,1,2,4)]
# 
# ggplot(MDS_plot, aes(x=Dim1, y=Dim2, color = treatment)) + 
#   geom_point() +
#   scale_color_manual(values = custom_jco) +
#   labs(x = dim1_label,
#        y = dim2_label) +
#   geom_dl(aes(label = treatment),
#           method = "smart.grid") +
#   coord_cartesian(clip = "off") +
#   theme(aspect.ratio = 1,
#         legend.position = "left",
#         legend.text = element_text(size = 10),
#         legend.text.align = 0,
#         legend.spacing.x = unit(0.5, "mm"),
#         legend.title = element_blank(),
#         legend.key=element_blank())
# 
# # Build model and test all against control (wt_ctr)
# design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
# 
# DGEL_object_filtered = estimateDisp(DGEL_object_filtered, design, robust=TRUE)
# 
# fit = glmQLFit(DGEL_object_filtered, design, robust=TRUE)
# 
# my_contrasts = makeContrasts(hb21i_vs_gus=hb21i-gus,
#                              hb40i_vs_gus=hb40i-gus,
#                              hb53i_vs_gus=hb53i-gus,
#                              levels=design)
# 
# test_list = list()
# 
# for(contrast in colnames(my_contrasts)) {
#   print(contrast)
#   test_list[[contrast]] = glmQLFTest(fit, contrast=my_contrasts[,contrast]) %>% topTags(n = Inf) %>% as.data.frame() %>% 
#     rename_with( ~ paste(.x, contrast, sep = "_"), .cols = c("logFC","logCPM","F","PValue","FDR"))
# }
# 
# merged_tests = test_list %>% purrr::reduce(left_join, by = c("Geneid","Chr","Start","End","Strand","Length"))
# 
# FDRts = 0.05 #set FDR threshold
# FCts = log2(2) #set Fold change threshold
# 
# fdr_colnames = colnames(merged_tests)[grepl("^FDR",colnames(merged_tests))]
# contrast_colnames = colnames(merged_tests)[grepl("^logFC",colnames(merged_tests))]
# 
# filtered_tests = merged_tests %>% 
#   filter(if_any(all_of(fdr_colnames), ~ (.) < FDRts)) %>% 
#   filter(if_any(all_of(contrast_colnames), ~ abs(.) > FCts))
# 
# # Add gene name and description to output file and remove extra columns
# extra_columns = colnames(merged_tests)[grepl(c("^logCPM|^F_|^PValue"),colnames(merged_tests))]
# filtered_tests_output = filtered_tests %>% add_gene_annotation %>% dplyr::select(-all_of(extra_columns))
# 
# write.table(filtered_tests_output, file = paste0("./output/",exp_name,"_filtered_tests_JR.txt"), row.names=F, sep="\t", quote=F, na="")
# ```
# 
# Extra code:
# ```{r}
# 
# ###### Use edgeR with macs2 consensus peaks for quantification
# # Merge peaks called in at least 2 replicates (adapted from https://ro-che.info/articles/2018-07-11-chip-seq-consensus)
# # Import MACS2 output. Select the least restrictive MACS2 peaks (no qvalue filter, q1)
# peak_file_list = list.files(path = "./input/", pattern="^BRC1_ChIP.*q1.*\\.narrowPeak$", full.names=TRUE)
# 
# peak_grangeslist = sapply(peak_file_list, read_narrowpeaks) %>% `names<-`(peak_file_list %>% str_extract("BRC1_ChIP*.")) %>% GRangesList
# 
# peak_coverage = coverage(peak_grangeslist)
# #peak_coverage
# 
# # Make GRanges and add column names to parse to GFF
# covered_ranges = IRanges::slice(peak_coverage, lower=2, rangesOnly=T) %>% GRanges %>% 
#   mutate(gene_id = paste0("peak_",rep(1:length(.)))) %>% 
#   mutate(name = gene_id) %>% 
#   mutate(type = rep("gene",length(.)))
# 
# write_bed(covered_ranges, file = "./output/macs2_consensus.bed")
# write_gff3(covered_ranges, file = "./output/macs2_consensus.gff")
# 
# 
# ###### Use edgeR with macs2 consensus peaks for quantification
# ## To do peak calling with MACS with high qvalue threshold to obtain peaks that are not enriched for edgeR
# 
# 
# # Use edgeR with macs2 consensus peaks for quantification
# feature_counts = fread("./input/2022_03_10_feature_counts_macs2_consensus.txt")
# feature_counts = feature_counts[,c(1:6,10:12,7:9)]
# 
# # Extract data to build DGEList object to process with edgeR
# sample_names = c("Input2","Input3","Input7",
#                  "ChIP2","ChIP3","ChIP7")
# 
# counts = feature_counts %>% dplyr::select(-c(Geneid,Chr,Start,End,Strand,Length)) %>% `colnames<-`(sample_names)
# gene_info = feature_counts %>% dplyr::select(c(Geneid,Chr,Start,End,Strand,Length))
# sample_groups = gsub('.{1}$', '', sample_names) %>% factor(levels=unique(gsub('.{1}$', '', sample_names)))
# 
# # Build DGEList object and normalize by library size
# DGEL_object = DGEList(counts = counts, 
#                       genes = gene_info,
#                       group = sample_groups) %>% calcNormFactors()
# 
# ##
# # DGEL_object = DGEL_object[filterByExpr(DGEL_object), ,keep.lib.sizes=FALSE] #remove genes with low counts and recalculate library size
# # 
# # DGEL_object = calcNormFactors(DGEL_object)
# 
# 
# design = model.matrix(~sample_groups)
# 
# DGEL_object <- estimateDisp(DGEL_object, design, robust=TRUE)
# fit <- glmQLFit(DGEL_object, design, robust=TRUE)
# results <- glmQLFTest(fit)
# 
# edgeR_MACS2_output = as.data.frame(results) %>% 
#   # filter(PValue < 0.05) %>% 
#   #dplyr::rename(name = "Geneid", score = "logFC") %>% 
#   mutate(name = paste0(Geneid,"_logFC_",round(logFC,3))) %>% GRanges
# 
# write_bed(edgeR_MACS2_output, file="./output/edgeR_MACS2_logFC.bed")
# 
# edgeR_MACS2_output = as.data.frame(results) %>% 
#   # filter(PValue < 0.05) %>% 
#   #dplyr::rename(name = "Geneid", score = "logFC") %>% 
#   mutate(name = paste0(Geneid,"_PVal_",round(PValue,4))) %>% GRanges
# 
# write_bed(edgeR_MACS2_output, file="./output/edgeR_MACS2_PVal.bed")



### map to entrez id
# names(genes_up)
# 
# db_ensembl_id = AnnotationDbi::select(org.At.tair.db,
#                                            column = "ENTREZID",
#                                            keys = names(genes_up),
#                                            keytype = "TAIR",
#                                            multiVals = "first")
# 
# 
# bm_ensembl_id = getBM(attributes = c("tair_locus","entrezgene_id"),
#                             filters = "tair_locus",
#                             values = names(genes_up),
#                             mart = ensembl)
# 
# test = full_join(db_ensembl_id,bm_ensembl_id, by = c("TAIR" = "tair_locus"))
# ###
# pathways.list <- keggList("pathway", "ath")
# 
# pathway.codes <- sub("path:", "", names(pathways.list)) 
# 
# genes.by.pathway <- sapply(pathway.codes,
#     function(pwid){
#         pw <- keggGet(pwid)
#         if (is.null(pw[[1]]$GENE)) return(NA)
#         pw2 <- pw[[1]]$GENE[c(TRUE,FALSE)] # may need to modify this to c(FALSE, TRUE) for other organisms
#         pw2 <- unlist(lapply(strsplit(pw2, split = ";", fixed = T), function(x)x[1]))
#         return(pw2)
#     }
# )
# head(genes.by.pathway)
# 
# test2 = test %>% filter(!is.na(ENTREZID)) %>% pull(TAIR)
# 
# for(g in test2){
#   print(any(sapply(genes.by.pathway,function(x) g %in% x)))
# }
# 
# ###


# #  Pair-wise comparisons
# design = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
# 
# contr = makeContrasts(hb21ivsgus = hb21i - gus,
#                       hb40ivsgus = hb40i - gus,
#                       hb53ivsgus = hb53i - gus,
#                       levels = design)
# 
# DGL_object_filtered = estimateDisp(DGL_object_filtered, design, robust=TRUE)
# 
# fit = glmQLFit(DGL_object_filtered, design, robust=TRUE)
# 
# qlf_test = glmQLFTest(fit, contrast = contr) 
# 
# FDRts = 0.05 #set FDR threshold
# FCts = log2(2) #set Fold change threshold
# 
# all_vs_ctr = topTags(qlf_test, n = Inf, p.value = FDRts)
# 
# 
# 
# 
# 
# 
# 
# 
# ##############
# # Build model and make contrasts to obtain FC
# 
# design_pairwise = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
# 
# # To do make contrasts and loop edgeR through each contrast
# design.pairs <-
# function(levels) {
# n <- length(levels)
# design <- matrix(0,n,choose(n,2))
# rownames(design) <- levels
# colnames(design) <- 1:choose(n,2)
# k <- 0
# for (i in 1:(n-1))
# for (j in (i+1):n) {
# k <- k+1
# design[i,k] <- 1
# design[j,k] <- -1
# colnames(design)[k] <- paste(levels[i],"-",levels[j],sep="")
# }
# design
# }
# 
# #make contrasts and use in edgeR loop and join results by gene_id
# unique(sample_groups) %>% design.pairs
# 
# # correct p-val with p.adjust(p, method = "fdr")   p = unadjusted pvalue of all comparisons

# superscript_function = function(x){
#   a = str_sub(x,1,-4)
#   b = str_sub(x,-3,-1)
#   paste0(a,"^",b)
# }


# To check which method of geom_dl work best

# label_methods = c("ahull.grid","chull.grid","extreme.grid","smart.grid")
# 
# plot_label_methods = function(method) {
#   ggplot(data = RPKM_PCA_PLOT, aes(x = PC1, y = PC2, color = genotype)) +
#     geom_point(alpha = 1) +
#     geom_dl(aes(label = genotype),
#             method = method) +
#     labs(title = method,
#          color = "Treatment",
#          x = paste0("PC1: ",round(RPKM_PCA_pv[1],2),"% var"),
#          y = paste0("PC2: ",round(RPKM_PCA_pv[2],2),"% var")) +
#     scale_color_manual(values = custom_jco) +
#     scale_fill_manual(values = custom_jco) +
#     coord_cartesian(clip = "off") +
#     theme(aspect.ratio = 1,
#           legend.position = "left",
#           legend.text = element_text(size = 10),
#           legend.spacing.x = unit(0.5, "mm"),
#           legend.title.align = 0.5,
#           legend.key=element_blank())
# }
# 
# myplots <- lapply(label_methods, plot_label_methods)
# grid.arrange(grobs = myplots)


#####
# Build model and make contrasts to obtain FC

# design_pairwise = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))
# 
# # To do make contrasts and loop edgeR through each contrast
# design.pairs <-
# function(levels) {
# n <- length(levels)
# design <- matrix(0,n,choose(n,2))
# rownames(design) <- levels
# colnames(design) <- 1:choose(n,2)
# k <- 0
# for (i in 1:(n-1))
# for (j in (i+1):n) {
# k <- k+1
# design[i,k] <- 1
# design[j,k] <- -1
# colnames(design)[k] <- paste(levels[i],"-",levels[j],sep="")
# }
# design
# }
# 
# #make contrasts and use in edgeR loop and join results by gene_id
# unique(sample_groups) %>% design.pairs
```

OLD Experiment 1: wt, brc1, hb21hb40hb53; control/+ABA
```{r}
# Read featureCounts output
exp_name = "experiment_1_"
feature_counts = fread("./input/2022_03_05_feature_counts_experiment_1_gene_hisat2.txt")

# Extract data to build DGEList object to process with edgeR
sample_names = c("wt_ctr_1","wt_ctr_2","wt_ctr_3",
                 "wt_aba_1","wt_aba_2","wt_aba_3",
                 "tri_ctr_1","tri_ctr_2","tri_ctr_3",
                 "tri_aba_1","tri_aba_2","tri_aba_3",
                 "brc1_ctr_1","brc1_ctr_2","brc1_ctr_3",
                 "brc1_aba_1","brc1_aba_2","brc1_aba_3")
counts = feature_counts %>% dplyr::select(-c(Geneid,Chr,Start,End,Strand,Length)) %>% `colnames<-`(sample_names)
gene_info = feature_counts %>% dplyr::select(c(Geneid,Chr,Start,End,Strand,Length))
sample_groups = gsub('.{2}$', '', sample_names) %>% factor(levels=unique(gsub('.{2}$', '', sample_names)))

# Build DGEList object and normalize by library size
DGEL_object = DGEList(counts = counts, 
                      genes = gene_info,
                      group = sample_groups) %>% calcNormFactors()

# Create RPKM object
RPKM_object = rpkm(DGEL_object, gene.length = "Length") %>% as.data.frame %>% cbind("gene_id"=DGEL_object$genes$Geneid,.)

write.table(RPKM_object, file = paste0("./output/",exp_name,"RPKM.txt"), row.names=F, sep="\t", quote=F)

# Remove genes with low RPKM counts
RPKM_cutoff = 1

drop = DGEL_object %>% rpkm %>% rowMeans %>% `<`(RPKM_cutoff) %>% which #get index of genes below threshold

DGEL_object_filtered = DGEL_object[-drop, ,keep.lib.sizes=FALSE] %>% calcNormFactors

# PCA plot
RPKM = (rpkm(DGEL_object_filtered,log = T))
RPKM_PCA = prcomp(t(RPKM))
RPKM_PCA_pv = ((RPKM_PCA$sdev^2) / (sum(RPKM_PCA$sdev^2)))*100
RPKM_PCA_data = RPKM_PCA$x[,1:2]

RPKM_PCA_PLOT = RPKM_PCA_data %>% as.data.frame %>%
  rownames_to_column("SampleID") %>%
  separate(SampleID,into=c("genotype","replicate"), sep="_(?!.*_)",remove=FALSE) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(genotype = factor(genotype, levels = c("wt_ctr","wt_aba","tri_ctr","tri_aba","brc1_ctr","brc1_aba"))) %>% 
  mutate(genotype = recode(genotype, 
                           "wt_ctr" = "wt",
                           "wt_aba" = "wt + ABA",
                           "tri_ctr" = "hb21hb40hb53",
                           "tri_aba" = "hb21hb40hb53 + ABA",
                           "brc1_ctr" = "brc1",
                           "brc1_aba" = "brc1 + ABA"))

legend_labels = RPKM_PCA_PLOT$genotype %>% levels

custom_jco = c("#868686FF","#565656","#0073C2FF", "#005693","#EFC000FF", "#BE9800")

custom_jco = 1:6
RPKM_PCA_PLOT2 = RPKM_PCA_PLOT %>% filter(genotype %in% c("wt", "hb21hb40hb53", "brc1"))

PCA_plot = ggplot(data = RPKM_PCA_PLOT, aes(x = PC1, y = PC2, color = genotype)) +
  geom_point(alpha = 1) +
  # geom_dl(aes(label = genotype),
  #         method = "smart.grid") +
  labs(x = paste0("PC1: ",round(RPKM_PCA_pv[1],2),"% var"),
       y = paste0("PC2: ",round(RPKM_PCA_pv[2],2),"% var")) +
  scale_color_manual(values = custom_jco, labels = legend_labels) +
  scale_fill_manual(values = custom_jco) +
  coord_cartesian(clip = "off") +
  theme(aspect.ratio = 1,
        legend.position = "left",
        legend.text = element_text(size = 10),
        legend.text.align = 0,
        legend.spacing.x = unit(0.5, "mm"),
        legend.title = element_blank(),
        legend.key=element_blank())
  
# Build model and test all against control (wt_ctr)
design = model.matrix(~sample_groups) %>% `colnames<-`(levels(sample_groups))

DGEL_object_filtered = estimateDisp(DGEL_object_filtered, design, robust=TRUE)

fit = glmQLFit(DGEL_object_filtered, design, robust=TRUE)

qlf_test = glmQLFTest(fit, coef=2:6) #compares all the samples to the control (ANOVA-like test)

all_vs_ctr = topTags(qlf_test, n = Inf) #unfiltered data

FDRts = 0.05 #set FDR threshold
FCts = log2(2) #set Fold change threshold

contrast_colnames = colnames(qlf_test)[grepl("^logFC",colnames(qlf_test))]

all_vs_ctr = topTags(qlf_test, n = Inf, p.value = FDRts) %>% 
  data.frame %>% filter(if_any(all_of(contrast_colnames), ~ abs(.) > FCts))

# Add gene name and description to output file
all_vs_ctr_output = all_vs_ctr %>% add_gene_annotation

write.table(all_vs_ctr_output, file = paste0("./output/",exp_name,"all_vs_ctr.txt"), row.names=F, sep="\t", quote=F, na="")

###
counts2 = counts %>% dplyr::select(contains("ctr"))

sample_groups2 = gsub('.{2}$', '', colnames(counts2)) %>% factor(levels=unique(gsub('.{2}$', '', colnames(counts2))))

DGEL_object2 = DGEList(counts = counts2, 
                      genes = gene_info,
                      group = sample_groups2) %>% calcNormFactors()

RPKM_cutoff = 1

drop = DGEL_object2 %>% rpkm %>% rowMeans %>% `<`(RPKM_cutoff) %>% which #get index of genes below threshold

DGEL_object2_filtered = DGEL_object2[-drop, ,keep.lib.sizes=FALSE] %>% calcNormFactors

# PCA plot
RPKM = (rpkm(DGEL_object2_filtered,log = T))
RPKM_PCA = prcomp(t(RPKM))
RPKM_PCA_pv = ((RPKM_PCA$sdev^2) / (sum(RPKM_PCA$sdev^2)))*100
RPKM_PCA_data = RPKM_PCA$x[,1:2]

RPKM_PCA_PLOT = RPKM_PCA_data %>% as.data.frame %>%
  rownames_to_column("SampleID") %>%
  separate(SampleID,into=c("genotype","replicate"), sep="_(?!.*_)",remove=FALSE) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(genotype = factor(genotype, levels = c("wt_ctr","tri_ctr","brc1_ctr"))) %>% 
  mutate(genotype = recode(genotype, 
                           "wt_ctr" = "wt",
                           "tri_ctr" = "hb21hb40hb53",
                           "brc1_ctr" = "brc1"))

legend_labels = RPKM_PCA_PLOT$genotype %>% levels

custom_jco = c("#868686FF","#0073C2FF", "#EFC000FF")

PCA_plot = ggplot(data = RPKM_PCA_PLOT, aes(x = PC1, y = PC2, color = genotype)) +
  geom_point(alpha = 1) +
  # geom_dl(aes(label = genotype),
  #         method = "smart.grid") +
  labs(x = paste0("PC1: ",round(RPKM_PCA_pv[1],2),"% var"),
       y = paste0("PC2: ",round(RPKM_PCA_pv[2],2),"% var")) +
  scale_color_manual(values = custom_jco, labels = legend_labels) +
  scale_fill_manual(values = custom_jco) +
  coord_cartesian(clip = "off") +
  theme(aspect.ratio = 1,
        legend.position = "left",
        legend.text = element_text(size = 10),
        legend.text.align = 0,
        legend.spacing.x = unit(0.5, "mm"),
        legend.title = element_blank(),
        legend.key=element_blank())

# Selected comparisons:
design = model.matrix(~sample_groups2) %>% `colnames<-`(levels(sample_groups2))

DGEL_object2_filtered = estimateDisp(DGEL_object2_filtered, design, robust=TRUE)

fit = glmQLFit(DGEL_object2_filtered, design, robust=TRUE)

qlf_test = glmQLFTest(fit, coef=2:3)

FDRts = 0.05 #set FDR threshold
FCts = log2(2) #set Fold change threshold

contrast_colnames = colnames(qlf_test)[grepl("^logFC",colnames(qlf_test))]

all_vs_ctr = topTags(qlf_test, n = Inf, p.value = FDRts) %>% 
  data.frame %>% filter(if_any(all_of(contrast_colnames), ~ abs(.) > FCts))

# Add gene name and description to output file
all_vs_ctr_output = all_vs_ctr %>% add_gene_annotation

### To do write output file
write.table(all_vs_ctr_output, file = paste0("./output/",exp_name,"brc1_tri_vs_ctr.txt"), row.names=F, sep="\t", quote=F, na="")

#####
# Build model and make contrasts to obtain FC

design_pairwise = model.matrix(~0+sample_groups) %>% `colnames<-`(levels(sample_groups))

# To do make contrasts and loop edgeR through each contrast
design.pairs <-
function(levels) {
n <- length(levels)
design <- matrix(0,n,choose(n,2))
rownames(design) <- levels
colnames(design) <- 1:choose(n,2)
k <- 0
for (i in 1:(n-1))
for (j in (i+1):n) {
k <- k+1
design[i,k] <- 1
design[j,k] <- -1
colnames(design)[k] <- paste(levels[i],"-",levels[j],sep="")
}
design
}

#make contrasts and use in edgeR loop and join results by gene_id
unique(sample_groups) %>% design.pairs
```
